$ErrorActionPreference = 'Stop'
$sourceCommit = 'e67aa992be5db412bd0437bb8afb95eedee0c9bc'
$sourceRoot = "https://raw.githubusercontent.com/fabd/diablo2/$sourceCommit/code/d2_113_data/"

function Read-GameTable([string]$name) {
    $raw = (Invoke-WebRequest -UseBasicParsing ($sourceRoot + $name + '.txt')).Content
    # Some original tables contain duplicate or empty column names.
    $lineEnd = $raw.IndexOf("`n")
    $seen = @{}
    $headers = @($raw.Substring(0, $lineEnd).TrimEnd("`r").Split("`t") | ForEach-Object {
        $key = $_
        if (!$key) { $key = 'unused' }
        if ($seen.ContainsKey($key)) { $seen[$key]++; $key + '__' + $seen[$key] }
        else { $seen[$key] = 0; $key }
    })
    return @($raw.Substring($lineEnd + 1) | ConvertFrom-Csv -Delimiter "`t" -Header $headers)
}

$supported = @('ac','ac%','ac/lvl','att','att%','att/lvl','att%/lvl','dmg%','dmg/lvl',
    'dmg-min','dmg-max','str','dex','enr','hp','mana','hp/lvl','mana/lvl','stam',
    'res-all','res-fire','res-cold','res-ltng','res-pois','res-pois-len',
    'balance1','balance2','balance3','block','block2','cast1','cast3',
    'swing1','swing2','swing3','move1','move2','move3','lifesteal','manasteal',
    'mag%','gold%','regen','mana-kill','red-dmg','red-mag','thorns','ease',
    'knock','noheal','ignore-ac','indestruct','half-freeze','regen-stam','stamdrain',
    'dmg-demon','dmg-undead','att-demon','att-undead','dmg-to-mana','pal','ama','sor','skilltab','sock',
    'fire-min','fire-max','cold-min','cold-max','cold-len','ltng-min','ltng-max',
    'dmg-fire','dmg-cold','dmg-ltng','dmg-pois')
$affixes = @()
foreach ($kind in @('prefix','suffix')) {
    $table = if ($kind -eq 'prefix') { 'MagicPrefix' } else { 'MagicSuffix' }
    $rowId = 0
    foreach ($row in (Read-GameTable $table)) {
        $rowId++
        if ($row.spawnable -ne '1' -or [int]$row.frequency -le 0 -or [int]$row.level -gt 99) { continue }
        $properties = @()
        $valid = $true
        foreach ($n in 1..3) {
            $code = $row."mod${n}code"
            if (!$code) { continue }
            $param = [int]$row."mod${n}param"
            if ($code -notin $supported -or ($code -eq 'skilltab' -and $param -notin @(0,1,2,3,4,5,9,10,11))) { $valid = $false; break }
            $properties += ,@($code, $param, [int]$row."mod${n}min", [int]$row."mod${n}max")
        }
        if (!$valid -or !$properties.Count) { continue }
        $affixes += [ordered]@{
            id = "$kind-$rowId"; kind = $kind; name = $row.Name; level = [int]$row.level
            maxLevel = [int]$row.maxlevel; requiredLevel = [int]$row.levelreq
            rare = ($row.rare -eq '1'); frequency = [int]$row.frequency; group = [int]$row.group
            include = @(1..7 | ForEach-Object { $row."itype$_" } | Where-Object { $_ })
            exclude = @(1..5 | ForEach-Object { $row."etype$_" } | Where-Object { $_ })
            properties = $properties
        }
    }
}
$types = [ordered]@{}
foreach ($row in (Read-GameTable 'ItemTypes')) {
    if (!$row.Code) { continue }
    $types[$row.Code] = [ordered]@{ parents = @($row.Equiv1,$row.Equiv2) | Where-Object { $_ }; sockets = @([int]$row.MaxSock1,[int]$row.MaxSock25,[int]$row.MaxSock40) }
    $types[$row.Code].parents = @($types[$row.Code].parents)
}
$bases = [ordered]@{}
foreach ($table in @('Weapons','Armor','Misc')) {
    foreach ($row in (Read-GameTable $table)) {
        if (!$row.code -or !$row.type -or ($table -eq 'Misc' -and $row.code -notin @('rin','amu','cm1','cm2','cm3'))) { continue }
        $bases[$row.code] = [ordered]@{ name = $row.name; type = $row.type; level = [int]$row.level; requiredLevel = [int]$row.levelreq; magicLevel = [int]$row.magiclvl; sockets = [int]$row.gemsockets }
    }
}
$out = @(
    '// Generated by scripts/import-affixes.ps1 from pinned original LoD 1.13 tables.'
    '// Do not edit generated values; see docs/affixes.md for supported mechanics.'
    'export type AffixProperty = [code: string, param: number, min: number, max: number];'
    "export type AffixDefinition = { id: string; kind: 'prefix' | 'suffix'; name: string; level: number; maxLevel: number; requiredLevel: number; rare: boolean; frequency: number; group: number; include: string[]; exclude: string[]; properties: AffixProperty[] };"
    "export const AFFIX_SOURCE_COMMIT = '$sourceCommit';"
    'export const AFFIX_DATA: AffixDefinition[] = ['
    ($affixes | ForEach-Object { '  ' + ($_ | ConvertTo-Json -Depth 8 -Compress) + ',' })
    '];'
    ('export const AFFIX_TYPES: Record<string, { parents: string[]; sockets: number[] }> = ' + ($types | ConvertTo-Json -Depth 8 -Compress) + ';')
    ('export const AFFIX_BASES: Record<string, { name: string; type: string; level: number; requiredLevel: number; magicLevel: number; sockets: number }> = ' + ($bases | ConvertTo-Json -Depth 8 -Compress) + ';')
)
$outputPath = Join-Path $PSScriptRoot '../src/affix-data.ts'
[IO.File]::WriteAllText($outputPath, ($out -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Imported $($affixes.Count) supported affixes and $($bases.Count) base profiles from $sourceCommit."
