$ErrorActionPreference = 'Stop'
$chestCommit = 'e67aa992be5db412bd0437bb8afb95eedee0c9bc'
$chestRoot = "https://raw.githubusercontent.com/fabd/diablo2/$chestCommit/code/d2_113_data/"
function Read-ChestTable([string]$name) {
    $raw = (Invoke-WebRequest -UseBasicParsing ($chestRoot + $name + '.txt')).Content
    if ($raw -is [byte[]]) { $raw = [Text.Encoding]::UTF8.GetString($raw) }
    $lineEnd = $raw.IndexOf("`n"); $seen = @{}
    $headers = @($raw.Substring(0, $lineEnd).TrimEnd("`r").Split("`t") | ForEach-Object {
        $key = $_; if (!$key) { $key = 'unused' }
        if ($seen.ContainsKey($key)) { $seen[$key]++; $key + '__' + $seen[$key] } else { $seen[$key] = 0; $key }
    })
    return @($raw.Substring($lineEnd + 1) | ConvertFrom-Csv -Delimiter "`t" -Header $headers)
}
$tables = Read-ChestTable 'TreasureClassEx'; $byName = @{}
foreach ($row in $tables) { $byName[$row.'Treasure Class'] = $row }
$included = @{}; $leaves = @{}
function Include-ChestTable([string]$name) {
    if ($included.ContainsKey($name)) { return }
    if (!$byName.ContainsKey($name)) { $leaves[$name] = $true; return }
    $included[$name] = $true; $row = $byName[$name]
    foreach ($i in 1..10) { if ($row."Item$i") { Include-ChestTable $row."Item$i" } }
}
foreach ($row in $tables) { if ($row.'Treasure Class' -match '^Act [1-5]( \([NH]\))? Chest [ABC]$') { Include-ChestTable $row.'Treasure Class' } }
$treasures = @($tables | Where-Object { $included.ContainsKey($_.'Treasure Class') } | ForEach-Object {
    $row = $_; $entries = @()
    foreach ($i in 1..10) { if ($row."Item$i") { $entries += ,@([string]$row."Item$i", [int]$row."Prob$i") } }
    [ordered]@{ id = $row.'Treasure Class'; level = [int]$row.level; picks = [int]$row.Picks; noDrop = [int]$row.NoDrop; entries = $entries }
})
Add-Type -AssemblyName System.Web.Extensions
Add-Type -AssemblyName Microsoft.VisualBasic
$decoder = New-Object System.Web.Script.Serialization.JavaScriptSerializer; $decoder.MaxJsonLength = 20000000
$locale = (Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/blizzhackers/d2data/fc469993502d0498809b9fc1af140ee2a9eb8902/json/localestrings-chi.json').Content
if ($locale -is [byte[]]) { $locale = [Text.Encoding]::UTF8.GetString($locale) }
$names = $decoder.DeserializeObject($locale)
$miscRows = @(Read-ChestTable 'Misc') + @(Read-ChestTable 'Weapons')
$misc = @($miscRows | Where-Object { $leaves.ContainsKey($_.code) -and $_.code -notmatch '^(gld|r\d\d|rin|amu|jew|cm[123])$' } | ForEach-Object {
    $name = $_.name
    if ($names.ContainsKey($_.namestr)) { $name = [Microsoft.VisualBasic.Strings]::StrConv($names[$_.namestr], [Microsoft.VisualBasic.VbStrConv]::SimplifiedChinese, 2052) }
    [ordered]@{ code = $_.code; name = $name; type = $_.type; value = [int]$_.cost; width = [int]$_.invwidth; height = [int]$_.invheight }
})
$ratios = @((Read-ChestTable 'ItemRatio') | Where-Object { $_.Version -eq '1' -and $_.Uber -eq '0' } | ForEach-Object {
    [ordered]@{ classSpecific = [bool][int]$_.'Class Specific'; unique = @([int]$_.Unique, [int]$_.UniqueDivisor, [int]$_.UniqueMin); set = @([int]$_.Set, [int]$_.SetDivisor, [int]$_.SetMin); rare = @([int]$_.Rare, [int]$_.RareDivisor, [int]$_.RareMin); magic = @([int]$_.Magic, [int]$_.MagicDivisor, [int]$_.MagicMin) }
})
$lines = @('// Generated by scripts/import-chests.ps1 from the same pinned LoD 1.13 tables as the item catalog.', "export const CHEST_SOURCE_COMMIT = '$chestCommit';", 'export type ChestTreasure = { id: string; level: number; picks: number; noDrop: number; entries: [string, number][] };', 'export type ChestMisc = { code: string; name: string; type: string; value: number; width: number; height: number };', 'export type ChestRatio = { classSpecific: boolean; unique: number[]; set: number[]; rare: number[]; magic: number[] };')
foreach ($entry in @(@('CHEST_TREASURES', 'ChestTreasure', $treasures), @('CHEST_MISC', 'ChestMisc', $misc), @('CHEST_RATIOS', 'ChestRatio', $ratios))) {
    $lines += "export const $($entry[0]): $($entry[1])[] = ["
    $lines += $entry[2] | ForEach-Object { '  ' + ($_ | ConvertTo-Json -Depth 8 -Compress) + ',' }
    $lines += '];'
}
[IO.File]::WriteAllText((Join-Path $PSScriptRoot '../src/chest-data.ts'), ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Imported $($treasures.Count) treasure tables, $($misc.Count) miscellaneous items and $($ratios.Count) quality ratios."
