$ErrorActionPreference = 'Stop'
$classCommit = 'e67aa992be5db412bd0437bb8afb95eedee0c9bc'
$classRoot = "https://raw.githubusercontent.com/fabd/diablo2/$classCommit/code/d2_113_data"
$classRaw = (Invoke-WebRequest -UseBasicParsing "$classRoot/Skills.txt").Content
if ($classRaw -is [byte[]]) { $classRaw = [Text.Encoding]::UTF8.GetString($classRaw) }
$classRows = $classRaw | ConvertFrom-Csv -Delimiter "`t" -WarningAction SilentlyContinue
function SkillId([string]$name) {
    $words = $name.Split(' ', [StringSplitOptions]::RemoveEmptyEntries)
    return $words[0].ToLowerInvariant() + (($words | Select-Object -Skip 1) -join '')
}
$classLines = @(
    "// Generated by scripts/import-class-skills.ps1 from LoD 1.13 Skills.txt ($classCommit)."
    'export type OriginalClassSkill = { number: number; name: string; classId: string; level: number; requires: string[]; element: string; min: number[]; max: number[]; shift: number; mana: number; manaStep: number; manaShift: number; minMana: number; length: number[]; params: number[]; synergy: string };'
    'export const ORIGINAL_CLASS_SKILLS: Record<string, OriginalClassSkill> = {'
)
foreach ($row in $classRows) {
    if ($row.charclass -notin @('ama','sor')) { continue }
    $entry = [ordered]@{
        number = [int]$row.Id; name = $row.skill; classId = $(if ($row.charclass -eq 'ama') { 'amazon' } else { 'sorceress' }); level = [int]$row.reqlevel
        requires = @(@($row.reqskill1, $row.reqskill2, $row.reqskill3) | Where-Object { $_ } | ForEach-Object { SkillId $_ })
        element = $row.EType; min = @([int]$row.EMin) + @(1..5 | ForEach-Object { [int]$row."EMinLev$_" }); max = @([int]$row.EMax) + @(1..5 | ForEach-Object { [int]$row."EMaxLev$_" })
        shift = [int]$row.HitShift; mana = [int]$row.mana; manaStep = [int]$row.lvlmana; manaShift = [int]$row.manashift; minMana = [int]$row.minmana
        length = @([int]$row.ELen, [int]$row.ELevLen1, [int]$row.ELevLen2, [int]$row.ELevLen3)
        params = @(1..8 | ForEach-Object { [int]$row."Param$_" }); synergy = $row.EDmgSymPerCalc
    }
    $classLines += '  ' + (ConvertTo-Json (SkillId $row.skill) -Compress) + ': ' + (ConvertTo-Json $entry -Depth 5 -Compress) + ','
}
$classLines += '};'
[IO.File]::WriteAllText((Join-Path $PSScriptRoot '../src/class-skill-data.ts'), ($classLines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output 'Imported 60 Amazon and Sorceress skill records.'
