$ErrorActionPreference = 'Stop'
$taskCommit = 'e67aa992be5db412bd0437bb8afb95eedee0c9bc'
$taskRaw = (Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/fabd/diablo2/$taskCommit/code/d2_113_data/Weapons.txt").Content
if ($taskRaw -is [byte[]]) { $taskRaw = [Text.Encoding]::UTF8.GetString($taskRaw) }
$taskRows = $taskRaw | ConvertFrom-Csv -Delimiter "`t" -WarningAction SilentlyContinue
$taskEntries = [ordered]@{}
foreach ($row in $taskRows) {
    if ($row.spawnable -ne '1' -or $row.type -notin @('bow','abow','xbow','jave','ajav','tkni','taxe')) { continue }
    $thrown = $row.type -in @('jave','ajav','tkni','taxe')
    $taskEntries[$row.code] = [ordered]@{
        kind = $(if ($row.type -eq 'xbow') { 'crossbow' } elseif ($row.type -in @('bow','abow')) { 'bow' } elseif ($row.type -in @('jave','ajav')) { 'javelin' } elseif ($row.type -eq 'taxe') { 'axe' } else { 'knife' })
        min = $(if ($thrown) { [int]$row.minmisdam } else { [int]$row.'2handmindam' })
        max = $(if ($thrown) { [int]$row.maxmisdam } else { [int]$row.'2handmaxdam' })
        strength = [int]$row.StrBonus; dexterity = [int]$row.DexBonus; stack = [int]$row.maxstack
    }
}
$taskLines = @(
    "// Generated by scripts/import-ranged.ps1 from LoD 1.13 Weapons.txt ($taskCommit)."
    "export type RangedKind = 'bow' | 'crossbow' | 'javelin' | 'knife' | 'axe';"
    'export type RangedBase = { kind: RangedKind; min: number; max: number; strength: number; dexterity: number; stack: number };'
    'export const RANGED_BASES: Record<string, RangedBase> = {'
)
foreach ($code in $taskEntries.Keys) { $taskLines += '  ' + (ConvertTo-Json $code -Compress) + ': ' + (ConvertTo-Json $taskEntries[$code] -Compress) + ',' }
$taskLines += '};'
[IO.File]::WriteAllText((Join-Path $PSScriptRoot '../src/ranged-data.ts'), ($taskLines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Imported $($taskEntries.Count) ranged weapon bases."
