import type { ItemBase, Mods, RuneId, RuneWord, SpecialItem } from './items.ts';

export const EXPANSION_MOD_NAMES = {
  damageUndead: '对不死系伤害 %', attackUndead: '对不死系准确率', damageDemons: '对恶魔伤害 %', attackDemons: '对恶魔准确率',
  goldFind: '额外金币 %', requirementReduction: '需求降低 %', indestructible: '无法破坏', ignoreDefense: '无视普通怪物防御',
  freezeTarget: '冻结目标秒数', blindTarget: '致盲目标秒数', flee: '击中逃跑几率 %', preventHeal: '阻止怪物治疗',
  maxLifePercent: '生命上限 %', maxFireRes: '最大火焰抗性', maxColdRes: '最大冰冷抗性', maxLightningRes: '最大闪电抗性', maxPoisonRes: '最大毒素抗性',
};
type Rune = { name: string; level: number; weapon: Mods; armor: Mods; shield: Mods };
const rune = (name: string, level: number, weapon: Mods, armor: Mods, shield = armor): Rune => ({ name, level, weapon, armor, shield });
export const EXTRA_RUNES: Partial<Record<RuneId, Rune>> = {
  eld: rune('艾德', 11, { damageUndead: 75, attackUndead: 50 }, { staminaDrain: 15 }, { block: 7 }),
  shael: rune('夏', 29, { ias: 20 }, { fhr: 20 }, { fbr: 20 }),
  dol: rune('多尔', 31, { flee: 25 }, { replenishLife: 7 }),
  hel: rune('海尔', 1, { requirementReduction: 20 }, { requirementReduction: 15 }),
  io: rune('艾欧', 35, { vitality: 10 }, { vitality: 10 }),
  lum: rune('卢姆', 37, { energy: 10 }, { energy: 10 }),
  ko: rune('科', 39, { dexterity: 10 }, { dexterity: 10 }),
  fal: rune('法尔', 41, { strength: 10 }, { strength: 10 }),
  lem: rune('蓝姆', 43, { goldFind: 75 }, { goldFind: 50 }),
  pul: rune('普尔', 45, { damageDemons: 75, attackDemons: 100 }, { enhancedDefense: 30 }),
  um: rune('乌姆', 47, { openWounds: 25 }, { allRes: 15 }, { allRes: 22 }),
  mal: rune('马尔', 49, { preventHeal: 1 }, { magicReduction: 7 }),
  ist: rune('伊司特', 51, { magicFind: 30 }, { magicFind: 25 }),
  gul: rune('古尔', 53, { attackRatingPercent: 20 }, { maxPoisonRes: 5 }),
  vex: rune('伐克斯', 55, { manaSteal: 7 }, { maxFireRes: 5 }),
  ohm: rune('欧姆', 57, { damage: 50 }, { maxColdRes: 5 }),
  lo: rune('罗', 59, { deadlyStrike: 20 }, { maxLightningRes: 5 }),
  sur: rune('瑟', 61, { blindTarget: 2 }, { maxManaPercent: 5 }, { mana: 50 }),
  ber: rune('贝', 63, { crushingBlow: 20 }, { damageReduction: 8 }),
  jah: rune('乔', 65, { ignoreDefense: 1 }, { maxLifePercent: 5 }, { life: 50 }),
  cham: rune('查姆', 67, { freezeTarget: 3 }, { cannotBeFrozen: 1 }),
  zod: rune('萨德', 69, { indestructible: 1 }, { indestructible: 1 }),
};
export const EXTRA_BASES: ItemBase[] = [
  { name: '巨战权杖', slot: 'weapon', weaponType: 'scepter', level: 21, power: 24, min: 10, max: 17, strength: 55, speed: -10, sockets: 5 },
  { name: '雄伟权杖', slot: 'weapon', weaponType: 'scepter', level: 15, power: 20, min: 8, max: 18, strength: 37, sockets: 3 },
  { name: '神圣权杖', slot: 'weapon', weaponType: 'scepter', level: 28, power: 37, min: 24, max: 29, strength: 58, sockets: 2 },
  { name: '神属权杖', slot: 'weapon', weaponType: 'scepter', level: 45, power: 53, min: 36, max: 44, strength: 103, speed: -10, sockets: 5 },
  { name: '炽天使之杖', slot: 'weapon', weaponType: 'scepter', level: 76, power: 93, min: 45, max: 54, strength: 108, dexterity: 69, sockets: 3 },
  { name: '神使之杖', slot: 'weapon', weaponType: 'scepter', level: 85, power: 98, min: 40, max: 49, strength: 97, dexterity: 70, speed: -10, sockets: 5 },
  { name: '长剑', slot: 'weapon', weaponType: 'sword', level: 20, power: 28, min: 3, max: 19, strength: 55, dexterity: 39, speed: -10, sockets: 4 },
  { name: '阔剑', slot: 'weapon', weaponType: 'sword', level: 15, power: 24, min: 7, max: 14, strength: 48, sockets: 4 },
  { name: '巨剑', slot: 'weapon', weaponType: 'sword', level: 33, power: 60, min: 25, max: 42, strength: 100, dexterity: 60, twoHanded: true, sockets: 6 },
  { name: '空间之刃', slot: 'weapon', weaponType: 'sword', level: 37, power: 40, min: 13, max: 35, strength: 85, dexterity: 60, sockets: 6 },
  { name: '战斗剑', slot: 'weapon', weaponType: 'sword', level: 33, power: 42, min: 16, max: 34, strength: 92, dexterity: 43, sockets: 4 },
  { name: '秘仪之剑', slot: 'weapon', weaponType: 'sword', level: 82, power: 85, min: 5, max: 77, strength: 99, dexterity: 109, speed: -10, sockets: 4 },
  { name: '巨神之刃', slot: 'weapon', weaponType: 'sword', level: 85, power: 150, min: 58, max: 115, strength: 189, dexterity: 110, twoHanded: true, sockets: 6 },
  { name: '手斧', slot: 'weapon', weaponType: 'axe', level: 1, power: 9, min: 3, max: 6, sockets: 2 },
  { name: '双刃斧', slot: 'weapon', weaponType: 'axe', level: 13, power: 24, min: 5, max: 13, strength: 43, sockets: 5 },
  { name: '纳卡', slot: 'weapon', weaponType: 'axe', level: 34, power: 52, min: 14, max: 36, strength: 85, sockets: 5 },
  { name: '狂战士斧', slot: 'weapon', weaponType: 'axe', level: 85, power: 94, min: 24, max: 71, strength: 138, dexterity: 59, sockets: 6 },
  { name: '钉头锤', slot: 'weapon', weaponType: 'mace', level: 8, power: 18, min: 3, max: 10, strength: 27, sockets: 2 },
  { name: '巨战之锤', slot: 'weapon', weaponType: 'hammer', level: 25, power: 42, min: 19, max: 29, strength: 53, speed: 20, sockets: 4 },
  { name: '铁皮鞭', slot: 'weapon', weaponType: 'mace', level: 43, power: 72, min: 13, max: 35, strength: 82, dexterity: 73, speed: -10, sockets: 5 },
  { name: '天罚之锤', slot: 'weapon', weaponType: 'hammer', level: 85, power: 110, min: 50, max: 61, strength: 189, speed: 20, sockets: 4 },
  { name: '锐利之斧', slot: 'weapon', weaponType: 'polearm', level: 21, power: 44, min: 13, max: 34, strength: 62, twoHanded: true, sockets: 4 },
  { name: '战戟', slot: 'weapon', weaponType: 'polearm', level: 29, power: 66, min: 12, max: 45, strength: 75, dexterity: 47, twoHanded: true, sockets: 6 },
  { name: '锐利之柱', slot: 'weapon', weaponType: 'polearm', level: 71, power: 100, min: 17, max: 165, strength: 114, dexterity: 33, twoHanded: true, sockets: 4 },
  { name: '巨长斧', slot: 'weapon', weaponType: 'polearm', level: 85, power: 140, min: 46, max: 127, strength: 179, dexterity: 99, twoHanded: true, sockets: 6 },
  { name: '塔盾', slot: 'shield', level: 22, power: 25, strength: 75, block: 54, smiteMin: 1, smiteMax: 5, sockets: 3 },
  { name: '歌德盾牌', slot: 'shield', level: 30, power: 35, strength: 60, block: 46, smiteMin: 2, smiteMax: 6, sockets: 3 },
  { name: '白骨盾牌', slot: 'shield', level: 19, power: 22, strength: 25, block: 50, smiteMin: 3, smiteMax: 6, sockets: 2 },
  { name: '饰金盾牌', slot: 'shield', level: 51, power: 169, strength: 89, block: 52, smiteMin: 20, smiteMax: 28, sockets: 4 },
  { name: '皇家盾牌', slot: 'shield', level: 55, power: 170, strength: 114, block: 55, smiteMin: 24, smiteMax: 32, sockets: 4 },
  { name: '统治者大盾', slot: 'shield', level: 72, power: 145, strength: 156, block: 52, smiteMin: 12, smiteMax: 34, sockets: 4 },
  { name: '旋风盾', slot: 'shield', level: 85, power: 220, strength: 148, block: 49, smiteMin: 5, smiteMax: 87, sockets: 4 },
  { name: '胸甲', slot: 'armor', level: 18, power: 68, strength: 30, sockets: 3 },
  { name: '哥德战甲', slot: 'armor', level: 32, power: 133, strength: 70, sockets: 4 },
  { name: '鬼魂战甲', slot: 'armor', level: 34, power: 118, strength: 38, sockets: 2 },
  { name: '织网战甲', slot: 'armor', level: 42, power: 214, strength: 92, sockets: 3 },
  { name: '圣堂武士外袍', slot: 'armor', level: 52, power: 260, strength: 118, sockets: 3 },
  { name: '灰暮寿衣', slot: 'armor', level: 65, power: 430, strength: 77, sockets: 4 },
  { name: '巨大鳞铠胸甲', slot: 'armor', level: 73, power: 480, strength: 116, sockets: 4 },
  { name: '皇冠', slot: 'helm', level: 29, power: 35, strength: 55, sockets: 3 },
  { name: '翼盔', slot: 'helm', level: 51, power: 98, strength: 115, sockets: 3 },
  { name: '恶魔头盖骨面具', slot: 'helm', level: 55, power: 130, strength: 102, sockets: 3 },
  { name: '骸骨面罩', slot: 'helm', level: 84, power: 150, strength: 106, sockets: 3 },
  { name: '轻型铁手套', slot: 'gloves', level: 20, power: 11, strength: 45 },
  { name: '战场手套', slot: 'gloves', level: 49, power: 45, strength: 88 },
  { name: '吸血鬼骸骨手套', slot: 'gloves', level: 63, power: 62, strength: 50 },
  { name: '吸血鬼獠牙腰带', slot: 'belt', level: 68, power: 60, strength: 50 },
  { name: '蛛网腰带', slot: 'belt', level: 61, power: 62, strength: 50 },
  { name: '巨战之靴', slot: 'boots', level: 54, power: 58, strength: 125 },
  { name: '圣甲虫壳靴', slot: 'boots', level: 66, power: 65, strength: 91 },
];
export const EXTRA_RUNEWORDS: RuneWord[] = [
  { name: '怨恨', runes: ['ith', 'el', 'eth'], slots: ['weapon'], mods: { damage: 33, maxDamage: 9, openWounds: 100, targetDefense: 25, preventHeal: 1, attackRating: 50 } },
  { name: '力量', runes: ['amn', 'tir'], slots: ['weapon'], mods: { damage: 35, crushingBlow: 25, lifeSteal: 7, manaOnKill: 2, strength: 20, vitality: 10 } },
  { name: '荣耀', runes: ['amn', 'el', 'ith', 'tir', 'sol'], slots: ['weapon'], mods: { damage: 160, minDamage: 9, maxDamage: 9, deadlyStrike: 25, attackRating: 250, allSkills: 1, lifeSteal: 7, replenishLife: 10, strength: 10, manaOnKill: 2 } },
  { name: '国王之恩典', runes: ['amn', 'ral', 'thul'], slots: ['weapon'], weaponTypes: ['sword', 'scepter'], mods: { damage: 100, damageDemons: 100, damageUndead: 50, fireDamage: 17, coldDamage: 9, attackRating: 150, attackDemons: 100, attackUndead: 100, lifeSteal: 7 } },
  { name: '黑色', runes: ['thul', 'io', 'nef'], slots: ['weapon'], weaponTypes: ['mace', 'hammer'], mods: { damage: 120, crushingBlow: 40, attackRating: 200, coldDamage: 9, vitality: 10, ias: 15, knockback: 1, magicReduction: 2 } },
  { name: '押韵', runes: ['shael', 'eth'], slots: ['shield'], mods: { block: 20, fbr: 40, allRes: 25, manaRegen: 15, cannotBeFrozen: 1, goldFind: 50, magicFind: 25 } },
  { name: '灿烂', runes: ['eth', 'lum'], slots: ['shield'], mods: { allSkills: 1, fcr: 10, fbr: 20, enhancedDefense: 80, energy: 10, manaRegen: 15, goldFind: 50, magicFind: 20 } },
  { name: '烟雾', runes: ['nef', 'lum'], slots: ['armor'], mods: { enhancedDefense: 75, defense: 100, allRes: 50, fhr: 20, energy: 10 } },
  { name: '狮心', runes: ['hel', 'lum', 'fal'], slots: ['armor'], mods: { damage: 20, requirementReduction: 15, strength: 25, energy: 10, vitality: 20, dexterity: 15, life: 50, allRes: 30 } },
  { name: '财富', runes: ['lem', 'ko', 'tir'], slots: ['armor'], mods: { goldFind: 300, magicFind: 100, dexterity: 10, manaOnKill: 2 } },
  { name: '光辉', runes: ['nef', 'sol', 'ith'], slots: ['helm'], mods: { enhancedDefense: 75, defense: 30, energy: 10, vitality: 10, damageToMana: 15, magicReduction: 3, mana: 33, damageReductionFlat: 7, lightRadius: 5 } },
  { name: '强制', runes: ['shael', 'um', 'thul'], slots: ['armor'], mods: { fhr: 40, damage: 15, coldDamage: 90, crushingBlow: 15, openWounds: 33, enhancedDefense: 175, coldRes: 45, fireRes: 15, lightningRes: 15, poisonRes: 15 } },
  { name: '圣堂', runes: ['ko', 'ko', 'mal'], slots: ['shield'], mods: { fhr: 20, fbr: 20, block: 20, enhancedDefense: 145, dexterity: 20, allRes: 60, magicReduction: 7 } },
  { name: '橡树之心', runes: ['ko', 'vex', 'pul', 'thul'], slots: ['weapon'], weaponTypes: ['mace'], mods: { allSkills: 3, fcr: 40, damageDemons: 75, attackDemons: 100, coldDamage: 9, manaSteal: 7, dexterity: 10, replenishLife: 20, maxManaPercent: 15, allRes: 35 } },
  { name: '遵从', runes: ['hel', 'ko', 'thul', 'eth', 'fal'], slots: ['weapon'], weaponTypes: ['polearm'], mods: { damage: 370, fhr: 40, targetDefense: 25, coldDamage: 9, crushingBlow: 40, defense: 250, strength: 10, dexterity: 10, allRes: 25, requirementReduction: 20 } },
  { name: '弑君者', runes: ['mal', 'um', 'gul', 'fal'], slots: ['weapon'], weaponTypes: ['sword', 'axe'], mods: { damage: 250, ias: 30, targetDefense: 25, attackRatingPercent: 20, crushingBlow: 33, openWounds: 50, preventHeal: 1, strength: 10, goldFind: 40 } },
  { name: '誓约', runes: ['shael', 'pul', 'mal', 'lum'], slots: ['weapon'], weaponTypes: ['sword', 'axe', 'mace'], mods: { indestructible: 1, ias: 50, damage: 260, damageDemons: 75, attackDemons: 100, preventHeal: 1, energy: 10 } },
  { name: '寂静', runes: ['dol', 'eld', 'hel', 'ist', 'tir', 'vex'], slots: ['weapon'], mods: { damage: 200, damageUndead: 75, attackUndead: 50, requirementReduction: 20, ias: 20, allSkills: 2, allRes: 75, fhr: 20, manaSteal: 11, flee: 25, blindTarget: 3, manaOnKill: 2, magicFind: 30 } },
  { name: '悔恨', runes: ['eth', 'tir', 'lo', 'mal', 'ral'], slots: ['weapon'], weaponTypes: ['sword', 'axe'], mods: { ias: 35, damageFlat: 360, ignoreDefense: 1, targetDefense: 25, fireDamage: 17, deadlyStrike: 20, preventHeal: 1, manaOnKill: 2 } },
  { name: '死亡呼吸', runes: ['vex', 'hel', 'el', 'eld', 'zod', 'eth'], slots: ['weapon'], mods: { indestructible: 1, ias: 60, damage: 375, damageUndead: 200, attackUndead: 50, targetDefense: 25, attackRating: 50, lifeSteal: 13, manaSteal: 7, preventHeal: 1, strength: 30, dexterity: 30, vitality: 30, energy: 30, requirementReduction: 20 } },
];
export const EXTRA_UNIQUES: SpecialItem[] = [
  { name: '瑞克撒特的挽歌', base: '短剑', slot: 'weapon', rarity: 'unique', level: 5, power: 8, min: 2, max: 7, mods: { damage: 100, minDamage: 5, attackRatingPercent: 20, crushingBlow: 25, defense: 25, lightRadius: 2 } },
  { name: '罗瑟的愤怒', base: '巨战权杖', slot: 'weapon', rarity: 'unique', level: 28, power: 24, min: 10, max: 17, strength: 55, mods: { damage: 120, minDamage: 5, maxDamage: 10, damageDemons: 50, crushingBlow: 25, lightningRes: 30, offensiveSkills: 2 } },
  { name: '屠夫之瞳', base: '纳卡', slot: 'weapon', rarity: 'unique', level: 39, power: 52, min: 14, max: 36, strength: 85, mods: { damage: 175, ias: 30, deadlyStrike: 35, openWounds: 25 } },
  { name: '巴拉那之星', base: '恶魔流星锤', slot: 'weapon', rarity: 'unique', level: 65, power: 110, min: 43, max: 53, strength: 153, dexterity: 44, speed: 10, mods: { damage: 200, ias: 50, attackRatingPercent: 200, fireDamage: 100, coldDamage: 100, lightningDamage: 100, strength: 15, dexterity: 15 } },
  { name: '天堂之光', base: '神使之杖', slot: 'weapon', rarity: 'unique', level: 61, power: 98, min: 40, max: 49, strength: 97, mods: { damage: 280, ias: 20, crushingBlow: 33, targetDefense: 33, allSkills: 3 }, sockets: 2 },
  { name: '阿斯特龙之铁的保护区', base: '神使之杖', slot: 'weapon', rarity: 'unique', level: 66, power: 98, min: 40, max: 49, strength: 97, mods: { damage: 270, damageFlat: 65, combatSkills: 4, ias: 10, attackRatingPercent: 175, crushingBlow: 33, damageReductionFlat: 6 } },
  { name: '光之军刀', base: '幻化之刃', slot: 'weapon', rarity: 'unique', level: 58, power: 35, min: 31, max: 35, strength: 25, dexterity: 136, mods: { damage: 180, minDamage: 10, maxDamage: 30, lightningDamage: 60, ias: 20, ignoreDefense: 1, manaSteal: 6, indestructible: 1 } },
  { name: '巫师之刺', base: '骸骨小刀', slot: 'weapon', rarity: 'unique', level: 61, power: 49, min: 23, max: 49, strength: 38, dexterity: 75, mods: { fcr: 50, allRes: 75, maxManaPercent: 15, manaPerLevel: 2, manaRegen: 15, indestructible: 1 } },
  { name: '镶金盾', base: '圆盾', slot: 'shield', rarity: 'unique', level: 5, power: 5, strength: 12, block: 30, mods: { enhancedDefense: 100, allRes: 10, block: 20, magicFind: 25 } },
  { name: '摩西祝福之环', base: '圆形盾', slot: 'shield', rarity: 'unique', level: 31, power: 47, strength: 53, block: 42, mods: { enhancedDefense: 180, fbr: 30, block: 25, allRes: 25 }, sockets: 2 },
  { name: '暴风之盾', base: '统治者大盾', slot: 'shield', rarity: 'unique', level: 73, power: 145, strength: 156, block: 52, mods: { defensePerLevel: 3.75, fbr: 35, block: 25, damageReduction: 35, strength: 30, coldRes: 60, lightningRes: 25, indestructible: 1 } },
  { name: '守护天使', base: '圣堂武士外袍', slot: 'armor', rarity: 'unique', level: 45, power: 260, strength: 118, mods: { enhancedDefense: 180, allSkills: 1, fbr: 30, block: 20, maxFireRes: 15, maxColdRes: 15, maxLightningRes: 15, maxPoisonRes: 15 } },
  { name: '都瑞尔的壳', base: '护胸甲', slot: 'armor', rarity: 'unique', level: 41, power: 200, strength: 65, mods: { enhancedDefense: 180, lifePerLevel: 1, strength: 15, fireRes: 20, lightningRes: 20, poisonRes: 20, coldRes: 50, cannotBeFrozen: 1 } },
  { name: '盗贼皇冠', base: '巨皇冠', slot: 'helm', rarity: 'unique', level: 49, power: 100, strength: 103, mods: { enhancedDefense: 180, lifeSteal: 10, life: 50, mana: 35, dexterity: 25, fireRes: 33, goldFind: 90 } },
  { name: '吸血鬼的凝视', base: '残酷头盔', slot: 'helm', rarity: 'unique', level: 41, power: 63, strength: 58, mods: { enhancedDefense: 100, lifeSteal: 7, manaSteal: 7, damageReduction: 18, magicReduction: 12, coldDamage: 14 } },
  { name: '法师之拳', base: '轻型铁手套', slot: 'gloves', rarity: 'unique', level: 23, power: 11, strength: 45, mods: { enhancedDefense: 25, fcr: 20, manaRegen: 25, fireDamage: 4 } },
  { name: '卓古拉之握', base: '吸血鬼骸骨手套', slot: 'gloves', rarity: 'unique', level: 76, power: 62, strength: 50, mods: { enhancedDefense: 110, lifeSteal: 9, strength: 12, openWounds: 25, replenishLife: 10 } },
  { name: '长串之耳', base: '魔皮勋带', slot: 'belt', rarity: 'unique', level: 29, power: 35, strength: 20, mods: { enhancedDefense: 160, lifeSteal: 7, damageReduction: 13, magicReduction: 12 } },
  { name: '蜘蛛之网', base: '蛛网腰带', slot: 'belt', rarity: 'unique', level: 80, power: 62, strength: 50, mods: { enhancedDefense: 110, allSkills: 1, fcr: 20, maxManaPercent: 5 } },
  { name: '沙暴之旅', base: '圣甲虫壳靴', slot: 'boots', rarity: 'unique', level: 64, power: 65, strength: 91, mods: { enhancedDefense: 150, runWalk: 20, fhr: 20, strength: 13, vitality: 13, poisonRes: 60 } },
  { name: '战争旅者', base: '战场之靴', slot: 'boots', rarity: 'unique', level: 42, power: 45, strength: 95, mods: { enhancedDefense: 175, runWalk: 25, strength: 10, vitality: 10, minDamage: 15, maxDamage: 25, magicFind: 40 } },
  { name: '玛拉的万花筒', base: '项链', slot: 'amulet', rarity: 'unique', level: 67, power: 0, mods: { allSkills: 2, allRes: 25, strength: 5, dexterity: 5, vitality: 5, energy: 5 } },
  { name: '大君之怒', base: '项链', slot: 'amulet', rarity: 'unique', level: 65, power: 0, mods: { allSkills: 1, ias: 20, lightningRes: 35, deadlyStrike: 30, lightningDamage: 15 } },
  { name: '矮人之星', base: '戒指', slot: 'ring', rarity: 'unique', level: 45, power: 0, mods: { life: 40, stamina: 40, magicReduction: 13, fireRes: 20, goldFind: 100 } },
];
